[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "https://www.*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*/"
  to = "/:splat"
  status = 301
  force = true
